/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#E8F0FE',
          100: '#D3E3FD',
          500: '#1A73E8',
          700: '#0A3880',
        },
        secondary: {
          50: '#F1F5F9',
          100: '#E2E8F0',
          500: '#4A5568',
        },
        surface: {
          50: '#F8FAFC',
          100: '#F1F5F9',
          default: '#FFFFFF',
        },
        status: {
          passed: '#16A34A',
          'passed-bg': '#DCFCE7',
          failed: '#DC2626',
          'failed-bg': '#FEE2E2',
          blocked: '#EA580C',
          'blocked-bg': '#FED7AA',
          skipped: '#6B7280',
          'skipped-bg': '#F3F4F6',
          'in-progress': '#2563EB',
          'in-progress-bg': '#DBEAFE',
        },
        priority: {
          critical: '#DC2626',
          high: '#EA580C',
          medium: '#CA8A04',
          low: '#16A34A',
        },
      },
      spacing: {
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
        12: '48px',
        16: '64px',
      },
      borderRadius: {
        xs: '2px',
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
      },
      fontSize: {
        'display-large': ['57px', { lineHeight: '64px', fontWeight: '400' }],
        'headline-large': ['32px', { lineHeight: '40px', fontWeight: '400' }],
        'headline-medium': ['28px', { lineHeight: '36px', fontWeight: '400' }],
        'headline-small': ['24px', { lineHeight: '32px', fontWeight: '400' }],
        'title-large': ['22px', { lineHeight: '28px', fontWeight: '500' }],
        'title-medium': ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'title-small': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'body-large': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-medium': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-small': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-large': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-medium': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-small': ['11px', { lineHeight: '16px', fontWeight: '500' }],
      },
      boxShadow: {
        'elevation-1': '0 1px 2px rgba(0,0,0,0.08)',
        'elevation-2': '0 2px 4px rgba(0,0,0,0.10)',
        'elevation-3': '0 4px 8px rgba(0,0,0,0.12)',
        'elevation-4': '0 8px 16px rgba(0,0,0,0.14)',
        'elevation-5': '0 16px 32px rgba(0,0,0,0.16)',
      },
      fontFamily: {
        base: ['Pretendard', 'Inter', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
    },
  },
  plugins: [],
  darkMode: 'class',
}
